/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatifRouteImport } from './routes/whatif'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RunwayRouteImport } from './routes/runway'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NetworthRouteImport } from './routes/networth'
import { Route as MerchantsRouteImport } from './routes/merchants'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ImportRouteImport } from './routes/import'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DebtRouteImport } from './routes/debt'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'

const WhatifRoute = WhatifRouteImport.update({
  id: '/whatif',
  path: '/whatif',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RunwayRoute = RunwayRouteImport.update({
  id: '/runway',
  path: '/runway',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworthRoute = NetworthRouteImport.update({
  id: '/networth',
  path: '/networth',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsRoute = MerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtRoute = DebtRouteImport.update({
  id: '/debt',
  path: '/debt',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/automation': typeof AutomationRoute
  '/calendar': typeof CalendarRoute
  '/categories': typeof CategoriesRoute
  '/debt': typeof DebtRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/forecast': typeof ForecastRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/insights': typeof InsightsRoute
  '/merchants': typeof MerchantsRoute
  '/networth': typeof NetworthRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/review': typeof ReviewRoute
  '/rules': typeof RulesRoute
  '/runway': typeof RunwayRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/wallet': typeof WalletRoute
  '/whatif': typeof WhatifRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/automation': typeof AutomationRoute
  '/calendar': typeof CalendarRoute
  '/categories': typeof CategoriesRoute
  '/debt': typeof DebtRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/forecast': typeof ForecastRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/insights': typeof InsightsRoute
  '/merchants': typeof MerchantsRoute
  '/networth': typeof NetworthRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/review': typeof ReviewRoute
  '/rules': typeof RulesRoute
  '/runway': typeof RunwayRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/wallet': typeof WalletRoute
  '/whatif': typeof WhatifRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/automation': typeof AutomationRoute
  '/calendar': typeof CalendarRoute
  '/categories': typeof CategoriesRoute
  '/debt': typeof DebtRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/forecast': typeof ForecastRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/insights': typeof InsightsRoute
  '/merchants': typeof MerchantsRoute
  '/networth': typeof NetworthRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/review': typeof ReviewRoute
  '/rules': typeof RulesRoute
  '/runway': typeof RunwayRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/wallet': typeof WalletRoute
  '/whatif': typeof WhatifRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/ai'
    | '/auth'
    | '/automation'
    | '/calendar'
    | '/categories'
    | '/debt'
    | '/diagnostics'
    | '/forecast'
    | '/goals'
    | '/import'
    | '/insights'
    | '/merchants'
    | '/networth'
    | '/notifications'
    | '/onboarding'
    | '/review'
    | '/rules'
    | '/runway'
    | '/scan'
    | '/settings'
    | '/stats'
    | '/subscriptions'
    | '/wallet'
    | '/whatif'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/ai'
    | '/auth'
    | '/automation'
    | '/calendar'
    | '/categories'
    | '/debt'
    | '/diagnostics'
    | '/forecast'
    | '/goals'
    | '/import'
    | '/insights'
    | '/merchants'
    | '/networth'
    | '/notifications'
    | '/onboarding'
    | '/review'
    | '/rules'
    | '/runway'
    | '/scan'
    | '/settings'
    | '/stats'
    | '/subscriptions'
    | '/wallet'
    | '/whatif'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/ai'
    | '/auth'
    | '/automation'
    | '/calendar'
    | '/categories'
    | '/debt'
    | '/diagnostics'
    | '/forecast'
    | '/goals'
    | '/import'
    | '/insights'
    | '/merchants'
    | '/networth'
    | '/notifications'
    | '/onboarding'
    | '/review'
    | '/rules'
    | '/runway'
    | '/scan'
    | '/settings'
    | '/stats'
    | '/subscriptions'
    | '/wallet'
    | '/whatif'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  AutomationRoute: typeof AutomationRoute
  CalendarRoute: typeof CalendarRoute
  CategoriesRoute: typeof CategoriesRoute
  DebtRoute: typeof DebtRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  ForecastRoute: typeof ForecastRoute
  GoalsRoute: typeof GoalsRoute
  ImportRoute: typeof ImportRoute
  InsightsRoute: typeof InsightsRoute
  MerchantsRoute: typeof MerchantsRoute
  NetworthRoute: typeof NetworthRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ReviewRoute: typeof ReviewRoute
  RulesRoute: typeof RulesRoute
  RunwayRoute: typeof RunwayRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  WalletRoute: typeof WalletRoute
  WhatifRoute: typeof WhatifRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatif': {
      id: '/whatif'
      path: '/whatif'
      fullPath: '/whatif'
      preLoaderRoute: typeof WhatifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runway': {
      id: '/runway'
      path: '/runway'
      fullPath: '/runway'
      preLoaderRoute: typeof RunwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networth': {
      id: '/networth'
      path: '/networth'
      fullPath: '/networth'
      preLoaderRoute: typeof NetworthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants': {
      id: '/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof MerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debt': {
      id: '/debt'
      path: '/debt'
      fullPath: '/debt'
      preLoaderRoute: typeof DebtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  AutomationRoute: AutomationRoute,
  CalendarRoute: CalendarRoute,
  CategoriesRoute: CategoriesRoute,
  DebtRoute: DebtRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  ForecastRoute: ForecastRoute,
  GoalsRoute: GoalsRoute,
  ImportRoute: ImportRoute,
  InsightsRoute: InsightsRoute,
  MerchantsRoute: MerchantsRoute,
  NetworthRoute: NetworthRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ReviewRoute: ReviewRoute,
  RulesRoute: RulesRoute,
  RunwayRoute: RunwayRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  WalletRoute: WalletRoute,
  WhatifRoute: WhatifRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
